import { cx } from '@/utils/cx'
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Coffee Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <div className="grid h-full min-h-screen grid-rows-[auto_1fr_auto]">
        <header
          className={cx(
            'transition-y sticky z-50 bg-white p-4 duration-300',
          )}
        >
          This is header component
        </header>

        <main className="px-4">{children}</main>

        <div className="px-4 pb-4 pt-12">
          <footer>This is footer component</footer>
        </div>
        </div>
    </>
  )
}
